# Generated by Django 4.2.8 on 2023-12-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date',
            field=models.DateField(default='1999-04-19'),
            preserve_default=False,
        ),
    ]
